# -*- coding: utf-8 -*-
"""CMPSC 497.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sNNpfNOCnylyB3wyk3WKAz_1kg99svS
"""

!pip install pyactr torch aif360

# install dependencies
!pip install torch torchvision torchaudio
!pip install aif360

# libraries
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from aif360.datasets import BinaryLabelDataset
from aif360.algorithms.preprocessing import Reweighing

# load and preprocess Data
csv_path = '/content/Dataset_Ads.csv'
df = pd.read_csv(csv_path)

# encoding the categorical variables
categorical_cols = ['Gender', 'Location', 'Ad Type', 'Ad Topic', 'Ad Placement']
encoders = {col: LabelEncoder().fit(df[col]) for col in categorical_cols}
for col, encoder in encoders.items():
    df[col] = encoder.transform(df[col])

# for any missing values
df = df.dropna()

X = df[['Age', 'Income', 'Location', 'Ad Type', 'Ad Topic', 'Ad Placement', 'Clicks', 'Conversion Rate', 'CTR']]

# CTR > 0.05 considered clicked
y = (df['CTR'] > 0.05).astype(int)

# scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# split train / test
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# convert to torch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

# deep learning model for NN
class ClickingPrediction(nn.Module):
    def __init__(self):
        super(ClickingPrediction, self).__init__()
        self.fc1 = nn.Linear(9, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))
        return x

# instantiating the model
model = ClickingPrediction()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# training the model
epochs = 20
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 5 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# evaluating the model
model.eval()
with torch.no_grad():
    preds = model(X_test_tensor)
    preds_class = (preds > 0.5).float()
    accuracy = (preds_class == y_test_tensor).float().mean()
    print(f'\n Test Accuracy: {accuracy:.4f}')

# bias mitigation

# reweighing with AIF360
df['target'] = y

# only want the numerical numerical features
numerical_features = ['Age', 'Income', 'Location', 'Ad Type', 'Ad Topic', 'Ad Placement', 'Clicks', 'Conversion Rate', 'CTR', 'target', 'Gender'] # Include 'Gender' if it's already encoded
df_numerical = df[numerical_features]

dataset = BinaryLabelDataset(
    favorable_label=1,
    unfavorable_label=0,
    df=df_numerical, # Use the DataFrame with only numerical features
    label_names=['target'],
    protected_attribute_names=['Gender']
)

# reweighing
RW = Reweighing(unprivileged_groups=[{'Gender': 0}], privileged_groups=[{'Gender': 1}])
dataset_transf = RW.fit_transform(dataset)

print("Reweighing applied. Can retrain on balanced data.")


# ACT-R cognitive modeling
import random

class ClickingModel:
    def __init__(self):
        pass

    def should_click(self, features):
        """
        Basic ACT-R inspired rule:
        - Higher relevance (Health, Travel) + Video Ads -> More likely click
        - Low CTR ads -> Less likely click
        """
        ad_type = features['Ad Type']
        ad_topic = features['Ad Topic']
        ctr = features['CTR']

        base_prob = 0.2  # defaulting to low probability

        if ad_topic in [0, 1]:
            base_prob += 0.3
        if ad_type == 1:  # video ad
            base_prob += 0.2
        if ctr > 0.05:
            base_prob += 0.1

        # simulate click decision
        return random.random() < base_prob

# example scenarios
simulator = ClickingModel()

sample_data = df.sample(5)
for idx, row in sample_data.iterrows():
    features = {
        'Ad Type': row['Ad Type'],
        'Ad Topic': row['Ad Topic'],
        'CTR': row['CTR']
    }
    decision = simulator.should_click(features)
    print(f"Simulated Click Decision: {'Clicked' if decision else 'Skipped'} | True CTR: {row['CTR']:.4f}")

# dependencies
!pip install torch torchvision torchaudio
!pip install aif360

# libraries
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from aif360.datasets import BinaryLabelDataset
from aif360.algorithms.preprocessing import Reweighing

# load and preprocess data
def load_and_preprocess_data(filepath):
    csv_path = '/content/Dataset_Ads.csv'
    df = pd.read_csv(csv_path)

    # handle categorical variables
    categorical_cols = ['Gender', 'Location', 'Ad Type', 'Ad Topic', 'Ad Placement']
    encoders= {}

    for col in categorical_cols:
        encoder= LabelEncoder()
        df[col] = encoder.fit_transform(df[col])
        encoders[col] = encoder

    # missing values
    df= df.dropna()

    # features + target
    features = ['Age', 'Income', 'Location', 'Ad Type', 'Ad Topic', 'Ad Placement', 'Clicks', 'Conversion Rate', 'CTR']
    X= df[features]

    #  CTR > 0.05 = clicked
    y= (df['CTR'] > 0.05).astype(int)

    # scaling and splitting data
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    # kept the original indices for reference purposes
    train_idx = y_train.index
    test_idx = y_test.index

    # tensor conversion
    X_train_tensor= torch.tensor(X_train, dtype=torch.float32)
    y_train_tensor= torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)
    X_test_tensor= torch.tensor(X_test, dtype=torch.float32)
    y_test_tensor= torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)
    return df, X_train_tensor, y_train_tensor, X_test_tensor, y_test_tensor, train_idx, test_idx, scaler, encoders

# neural network
class ClickingPrediction(nn.Module):
    def __init__(self, input_size=9):
        super(ClickingPrediction, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x= self.relu(self.fc1(x))
        x= self.dropout(x)
        x= self.relu(self.fc2(x))
        x= self.sigmoid(self.fc3(x))
        return x

# training model
def train_model(model, X_train, y_train, epochs=20, learning_rate=0.001):
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        outputs = model(X_train)
        loss = criterion(outputs, y_train)
        loss.backward()
        optimizer.step()
        if (epoch+1) % 5 == 0:
            print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')
    return model

# evaluate model
def evaluate_model(model, X_test, y_test):
    model.eval()
    with torch.no_grad():
        preds = model(X_test)
        preds_class = (preds > 0.5).float()
        accuracy = (preds_class == y_test).float().mean()
        print(f'Test Accuracy: {accuracy:.4f}')
    return preds.squeeze().numpy()

# AIF360 bias mitigation
def bias_mitigation(df, target_col='target'):
    df['target'] = (df['CTR'] > 0.05).astype(int)
    numerical_features = ['Age', 'Income', 'Location', 'Ad Type', 'Ad Topic',
                          'Ad Placement', 'Clicks', 'Conversion Rate', 'CTR', 'target', 'Gender']
    df_numerical = df[numerical_features]
    dataset = BinaryLabelDataset(
        favorable_label=1,
        unfavorable_label=0,
        df=df_numerical,
        label_names=['target'],
        protected_attribute_names=['Income']
    )

    # reweighing
    RW = Reweighing(unprivileged_groups=[{'Income': 0}], privileged_groups=[{'Income': 1}])
    dataset_transformed = RW.fit_transform(dataset)
    print("Reweighing applied - mitigate socioeconomic bias in advertisement recs.")

    # turning back to dataframe
    df_fair = dataset_transformed.convert_to_dataframe()[0]
    sample_weights = dataset_transformed.instance_weights
    return df_fair, sample_weights

# ACT-R
class ClickingModel:
    def __init__(self):
        self.thresholds = {
            'Health': 0.7,   # High interest
            'Travel': 0.65,  # High interest
            'Food': 0.6,     # Moderate interest
            'Tech': 0.55,    # Moderate interest
            'Fashion': 0.5,  # Low interest
            'Native': 0.45   # Low interest
        }

    def simulate_click(self, user_features, ad_features):
        """Simulate human-like click decisions based on ACT-R"""

        # base click probability
        base_prob = 0.2

        # adjustments- age
        age = user_features.get('Age', 30)
        if 18 <= age <= 30:
            # Young users more likely to click on ads
            base_prob += 0.1

        # adjustments- ad type
        ad_type = ad_features.get('Ad Type')
        if ad_type == 'Video':
            base_prob += 0.15  # Video ads get more attention
        elif ad_type == 'Banner':
            base_prob += 0.05  # Banner ads get some attention

        # ad topic
        ad_topic = ad_features.get('Ad Topic')
        topic_threshold = self.thresholds.get(ad_topic, 0.5)

        # adjustments- location & placement
        if ad_features.get('Ad Placement') == 'Social Media':
            base_prob += 0.1  # Social media gets more attention

        # adding a random factor for variability in regular human behavior
        random_factor = random.uniform(-0.1, 0.1)

        final_prob = base_prob + random_factor

        # decision making part
        return final_prob > topic_threshold

# ad recommendation
def recommend_ads_for_user(user_features, ad_pool, model, scaler, encoders, top_n=3):
    """Recommend ads for a specific user"""
    ad_predictions= []

    # for each potential ad in ad pool
    for ad in ad_pool:
        feature_vector = [
            user_features['Age'],
            user_features['Income'],
            user_features['Location'],
            encoders['Ad Type'].transform([ad['Ad Type']])[0],  # Ad Type
            encoders['Ad Topic'].transform([ad['Ad Topic']])[0],  # Ad Topic
            encoders['Ad Placement'].transform([ad['Ad Placement']])[0],  # Ad Placement
            ad['Clicks'],
            ad['Conversion Rate'],
            ad['CTR']
        ]

        # scale
        scaled_features = scaler.transform([feature_vector])
        features_tensor = torch.tensor(scaled_features, dtype=torch.float32)

        # click probability (prediction)
        with torch.no_grad():
            click_prob = model(features_tensor).item()
        ad_predictions.append((ad, click_prob))
    ranked_ads = sorted(ad_predictions, key=lambda x: x[1], reverse=True)

    # top n recommendations
    return ranked_ads[:top_n]



# user details
def user_profiles(df):
    """Extract user profiles from dataset"""
    user_cols= ['Age', 'Gender', 'Income', 'Location']
    unique_users = df[user_cols].drop_duplicates().reset_index(drop=True)
    return unique_users

# ad pool from dataset
def extract_ad_pool(df):
    """Extract ads from dataset"""
    ad_cols = ['Ad Type', 'Ad Topic', 'Ad Placement', 'Clicks', 'Conversion Rate', 'CTR']
    unique_ads = df[ad_cols].drop_duplicates().reset_index(drop=True)
    return unique_ads



def main():

    file_path= "online_ad_clicks.csv"  # path to Mendeley dataset
    print("Loading and preprocessing data")
    df, X_train, y_train, X_test, y_test, train_idx, test_idx, scaler, encoders = load_and_preprocess_data(file_path)

    print("Mitigating bias")
    df_fair, sample_weights = bias_mitigation(df)

    print("Training model")
    model= ClickingPrediction()
    model= train_model(model, X_train, y_train)

    print("Evaluating model")
    predictions = evaluate_model(model, X_test, y_test)

    unique_users= user_profiles(df)
    ad_pool= extract_ad_pool(df)
    cognitive_model= ClickingModel()

    # sample user
    sample_user_idx= 0  # Take first user as example
    sample_user = unique_users.iloc[sample_user_idx].to_dict()

    # convert to int
    sample_user['Gender'] = int(sample_user['Gender'])
    sample_user['Location'] = int(sample_user['Location'])

    print("\nGenerating recommendations for sample user:")
    print(f"User: Age {sample_user['Age']}, Gender {encoders['Gender'].inverse_transform([sample_user['Gender']])[0]}, Location: {encoders['Location'].inverse_transform([sample_user['Location']])[0]}")

  # convert back to og for ad pool
    ad_pool_list= []
    for _, ad in ad_pool.iterrows():
        ad_dict = ad.to_dict()
        ad_dict['Ad Type'] = encoders['Ad Type'].inverse_transform([int(ad_dict['Ad Type'])])[0]
        ad_dict['Ad Topic'] = encoders['Ad Topic'].inverse_transform([int(ad_dict['Ad Topic'])])[0]
        ad_dict['Ad Placement'] = encoders['Ad Placement'].inverse_transform([int(ad_dict['Ad Placement'])])[0]
        ad_pool_list.append(ad_dict)

    recommendations= recommend_ads_for_user(sample_user, ad_pool_list, model, scaler, encoders)  # Pass encoders here

    print("\nTop recommended ads:")
    for i, (ad, prob) in enumerate(recommendations, 1):
        print(f"Recommendation {i}:")
        print(f"  Ad Type: {ad['Ad Type']}")
        print(f"  Ad Topic: {ad['Ad Topic']}")
        print(f"  Ad Placement: {ad['Ad Placement']}")
        print(f"  Predicted Click Probability: {prob:.4f}")

        # simulate cognitive model
        decision= cognitive_model.simulate_click(sample_user, ad)
        print(f"  Cognitive Model Decision: {'Will Click' if decision else 'Will Not Click'}")
        print()

if __name__ == "__main__":
    main()